### PR TITLE
Remove stale cookies from login page

### LINKED ISSUE #79: Frontend: Clear Login Cookies
- clear the user cookie when login fails
- redirect login to / when you're already logged in

### PR DESCRIPTION
**Pull request by WishingWell13**
# Info

Closes #79  (If there is no issue for this pull request yet, please create one or
delete this line if the pull request is for a very minor tweak).

# Description

What changes did you make? List all distinct problems that this PR addresses. Explain any relevant
motivation or context.

Bug fixes regarding cookies and the login page

## Changes

- clear the user cookie when login fails
- redirect login to / when you're already logged in

# Type of Change

- [x] Patch (non-breaking change/bugfix)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (A change to a README/description)
- [ ] Continuous Integration/DevOps Change (Related to deployment steps, continuous integration
      workflows, linting, etc.)
- [ ] Other: (Fill In) 

If you've selected Patch, Minor, or Major as your change type, **make sure to bump the version before merging in `package.json`!**
# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally.
- [ ] on the testing API/testing database.
- [ ] with appropriate Postman routes. Screenshots are included below.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [x] I have appropriately edited the API version in the `package.json` file.
- [x] My changes produce no new warnings.

# Screenshots

Please include a screenshot of your Postman testing passing successfully.

image

### CODE REVIEW

File: client/src/app/login/login.ts [hunk 1]
```diff
@@ -4,16 +4,22 @@ import { login as apiLogin } from '@/lib/api/UserAPI';
...
+import { cookies } from 'next/headers';
 import { redirect } from 'next/navigation';
+import { getCookie } from 'cookies-next';
 
 export async function login(email: string, password: string): Promise<string> {
   let response;
   try {
     response = await apiLogin(email, password);
   } catch (error) {
+    const cookieStore = await cookies();
```
Comment (angela139) [inline client/src/app/login/login.ts:16]: Maybe add this part as function like deleteCookie in the services/CookieService.ts for cleanliness

File: client/src/app/login/page.tsx [hunk 2]
```diff
@@ -34,9 +35,23 @@ export default function LoginPage() {
     // If successful, the page will redirect and the rest of this function will
     // not run
     const error = await login(credentials.email, credentials.password);
+
+    console.log(`Error: ${error}`);
```
Comment (angela139) [inline client/src/app/login/page.tsx:39]: Remove this

File: client/src/app/login/page.tsx [hunk 3]
```diff
@@ -34,9 +35,23 @@ export default function LoginPage() {
...
+    const userCookie = getCookie(CookieType.USER);
+
+    // Send the user to the dashboard page if they already have a valid cookie
+    if (userCookie) {
+      console.log('Already logged in');
+      redirect('/');
+    }
+  }, []);
+
+  const userCookie = getCookie(CookieType.USER);
```
Comment (angela139) [inline client/src/app/login/page.tsx:53]: Why is userCookie defined twice?

**Review by angela139 — COMMENTED** [review]
Looks pretty good to me! Just added some comments to clean up the code a bit

File: client/src/components/Logout/index.tsx
Comment (SheepTester) [inline client/src/components/Logout/index.tsx:1]: you can delete this, we switched to using a route handler instead

File: client/src/lib/api/UserAPI.ts [hunk 4]
```diff
@@ -15,6 +15,7 @@ import { getErrorMessage } from '../utils';
 
 export const login = async (email: string, password: string): Promise<LoginResponse> => {
   const requestUrl = `${config.api.baseUrl}${config.api.endpoints.auth.login}`;
+  console.log('requestUrl', requestUrl);
```
Comment (SheepTester) [inline client/src/lib/api/UserAPI.ts:18]: remove :pray:

File: server/README.md [hunk 5]
```diff
@@ -1,6 +1,7 @@
 ## Setup
 
 1. Copy `.env.example` to `.env` and fill in the values
+   1. If you are on ACM @ UCSD Dev Team, fields are available in our google drive for step 1 and 2
```
Comment (SheepTester) [inline server/README.md:4]: can you undo this change (so there are no changes to the server/ folder), otherwise I think merging your PR might take down both portals while the backend action runs

File: client/src/app/page.tsx [hunk 6]
```diff
@@ -12,7 +12,7 @@ export default async function Home() {
 
   if (!accessToken) {
     console.log('Dashboard broke: access token undefined');
-    redirect('/login');
+    redirect('/api/logout');
```
Comment (SheepTester) [inline client/src/app/page.tsx:15]: you might also need to update the application and profile edit pages

File: client/src/components/Logout/index.tsx
Comment (WishingWell13) [reply client/src/components/Logout/index.tsx:1]: Remind me what this method is formally called again?

Comment (SheepTester) [reply client/src/components/Logout/index.tsx:1]: don't really remember but route handler is the formal name

**Comment by WishingWell13** [comment]
https://github.com/user-attachments/assets/e95b4c31-3a2e-406f-aa86-9d992e441efb

File: client/src/app/page.tsx [hunk 7]
```diff
@@ -10,7 +10,8 @@ export default async function Home() {
   const accessToken = await getCookie(CookieType.ACCESS_TOKEN);
 
   if (!accessToken) {
-    redirect('/login');
+    console.log('Dashboard broke: access token undefined');
```
Comment (alexzhang1618) [inline client/src/app/page.tsx:13]: let's remove this console.log

File: client/src/app/login/page.tsx [hunk 8]
```diff
@@ -34,9 +33,20 @@ export default function LoginPage() {
...
+
     setError(error);
   };
 
+  useEffect(() => {
+    const userCookie = getCookie(CookieType.USER);
+
+    // Send the user to the dashboard page if they already have a valid cookie
+    if (userCookie) {
+      console.log('Already logged in');
```
Comment (alexzhang1618) [inline client/src/app/login/page.tsx:45]: here too

**Review by alexzhang1618 — APPROVED** [review]
If everything works in dev and preview then lgtm, two nits
