### PR TITLE
Fixed invalid password not showing after cookie clears

### LINKED ISSUE #79: Frontend: Clear Login Cookies
- clear the user cookie when login fails
- redirect login to / when you're already logged in

### PR DESCRIPTION
**Pull request by WishingWell13**
# Info

Closes #79. (If there is no issue for this pull request yet, please create one or
delete this line if the pull request is for a very minor tweak).

# Description

What changes did you make? List all distinct problems that this PR addresses. Explain any relevant
motivation or context.

Moved API logout call until after setting error message
## Changes

- Fixed bug where "invalid password" would no longer show

# Type of Change

- [x] Patch (non-breaking change/bugfix)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (A change to a README/description)
- [ ] Continuous Integration/DevOps Change (Related to deployment steps, continuous integration
      workflows, linting, etc.)
- [ ] Other: (Fill In) 

If you've selected Patch, Minor, or Major as your change type, **make sure to bump the version before merging in `package.json`!**
# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally.
- [ ] on the testing API/testing database.
- [ ] with appropriate Postman routes. Screenshots are included below.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [x] I have appropriately edited the API version in the `package.json` file.
- [x] My changes produce no new warnings.

# Screenshots

Please include a screenshot of your Postman testing passing successfully.

https://github.com/user-attachments/assets/413ab75e-a3d7-4a76-b00e-9a8ff8b64c17

### CODE REVIEW

File: client/src/app/login/page.tsx [hunk 1]
```diff
@@ -35,6 +35,7 @@ export default function LoginPage() {
     const error = await login(credentials.email, credentials.password);
 
     setError(error);
+    redirect('/api/logout');
```
Comment (alexzhang1618) [inline client/src/app/login/page.tsx:38]: We shouldn't be logging out, I don't think cookies will get set if this errors? Test it and see

**Review by alexzhang1618 — APPROVED** [review]
